/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type GalleryQuoteTile = {
  _type: "galleryQuoteTile";
  text: string;
  role: "feature" | "wide" | "tall" | "normal";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GalleryPhotoTile = {
  _type: "galleryPhotoTile";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role: "feature" | "wide" | "tall" | "normal";
};

export type PriceTier = {
  _type: "priceTier";
  label: string;
  price: number;
};

export type Dish = {
  _type: "dish";
  name: string;
  urdu?: string;
  desc?: string;
  price?: number;
  priceTiers?: Array<
    {
      _key: string;
    } & PriceTier
  >;
  spice?: 0 | 1 | 2 | 3;
  signature?: boolean;
};

export type MenuCategory = {
  _type: "menuCategory";
  categoryId: string;
  label: string;
  urdu: string;
  note?: string;
  sectionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dishes?: Array<
    {
      _key: string;
    } & Dish
  >;
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tiles?: Array<
    | ({
        _key: string;
      } & GalleryPhotoTile)
    | ({
        _key: string;
      } & GalleryQuoteTile)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categories?: Array<
    {
      _key: string;
    } & MenuCategory
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | GalleryQuoteTile
  | SanityImageAssetReference
  | GalleryPhotoTile
  | PriceTier
  | Dish
  | MenuCategory
  | GalleryPage
  | SanityImageCrop
  | SanityImageHotspot
  | Menu
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../src/sanity/queries.ts
// Variable: MENU_QUERY
// Query: *[_id == "menu"][0]{    categories[]{      _key,      categoryId,      label,      urdu,      note,      sectionImage{        asset->{          url,          metadata{ lqip, dimensions{ width, height } }        },        hotspot,        crop      },      dishes[]{        _key,        name,        urdu,        desc,        price,        priceTiers[]{ _key, label, price },        spice,        signature      }    }  }
export type MENU_QUERY_RESULT =
  | {
      categories: null;
    }
  | {
      categories: Array<{
        _key: string;
        categoryId: string;
        label: string;
        urdu: string;
        note: string | null;
        sectionImage: {
          asset: {
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        dishes: Array<{
          _key: string;
          name: string;
          urdu: string | null;
          desc: string | null;
          price: number | null;
          priceTiers: Array<{
            _key: string;
            label: string;
            price: number;
          }> | null;
          spice: 0 | 1 | 2 | 3 | null;
          signature: boolean | null;
        }> | null;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_id == "galleryPage"][0]{    tiles[]{      _key,      _type,      _type == "galleryPhotoTile" => {        role,        image{          asset->{            url,            metadata{ lqip, dimensions{ width, height } }          },          alt,          hotspot,          crop        }      },      _type == "galleryQuoteTile" => {        role,        text      }    }  }
export type GALLERY_QUERY_RESULT =
  | {
      tiles: null;
    }
  | {
      tiles: Array<
        | {
            _key: string;
            _type: "galleryPhotoTile";
            role: "feature" | "normal" | "tall" | "wide";
            image: {
              asset: {
                url: string;
                metadata: {
                  lqip: string | null;
                  dimensions: {
                    width: number;
                    height: number;
                  } | null;
                } | null;
              } | null;
              alt: string;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            };
          }
        | {
            _key: string;
            _type: "galleryQuoteTile";
            role: "feature" | "normal" | "tall" | "wide";
            text: string;
          }
      > | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "menu"][0]{\n    categories[]{\n      _key,\n      categoryId,\n      label,\n      urdu,\n      note,\n      sectionImage{\n        asset->{\n          url,\n          metadata{ lqip, dimensions{ width, height } }\n        },\n        hotspot,\n        crop\n      },\n      dishes[]{\n        _key,\n        name,\n        urdu,\n        desc,\n        price,\n        priceTiers[]{ _key, label, price },\n        spice,\n        signature\n      }\n    }\n  }\n': MENU_QUERY_RESULT;
    '\n  *[_id == "galleryPage"][0]{\n    tiles[]{\n      _key,\n      _type,\n      _type == "galleryPhotoTile" => {\n        role,\n        image{\n          asset->{\n            url,\n            metadata{ lqip, dimensions{ width, height } }\n          },\n          alt,\n          hotspot,\n          crop\n        }\n      },\n      _type == "galleryQuoteTile" => {\n        role,\n        text\n      }\n    }\n  }\n': GALLERY_QUERY_RESULT;
  }
}
