/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CateringPackage = {
  _type: "cateringPackage";
  name?: string;
  pricePerPerson?: number;
  featured?: boolean;
  items?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SitePhoto = {
  _type: "sitePhoto";
  key?:
    | "hero-carousel-1"
    | "hero-carousel-2"
    | "hero-carousel-3"
    | "hero-carousel-4"
    | "founder"
    | "food-bbq"
    | "food-karahi"
    | "food-nihari"
    | "food-spread"
    | "catering"
    | "parallax"
    | "must-try-4"
    | "occasion-corporate-lunch"
    | "occasion-walima"
    | "occasion-mehndi"
    | "occasion-daawat"
    | "occasion-community-mosque"
    | "occasion-dinner-party"
    | "occasion-birthday-party"
    | "occasion-anniversary"
    | "occasion-corporate-events";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  caption?: string;
  tag?: "hero" | "food" | "occasion" | "people" | "venue" | "moment";
};

export type GalleryQuoteTile = {
  _type: "galleryQuoteTile";
  text?: string;
  role?: "feature" | "wide" | "tall" | "normal";
};

export type GalleryPhotoTile = {
  _type: "galleryPhotoTile";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  role?: "feature" | "wide" | "tall" | "normal";
};

export type PriceTier = {
  _type: "priceTier";
  label?: string;
  price?: number;
};

export type Dish = {
  _type: "dish";
  name?: string;
  urdu?: string;
  desc?: string;
  price?: number;
  priceTiers?: Array<
    {
      _key: string;
    } & PriceTier
  >;
  spice?: 0 | 1 | 2 | 3;
  signature?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  featuredOrder?: number;
};

export type MenuCategory = {
  _type: "menuCategory";
  categoryId?: string;
  label?: string;
  urdu?: string;
  note?: string;
  sectionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dishes?: Array<
    {
      _key: string;
    } & Dish
  >;
};

export type CateringPackages = {
  _id: string;
  _type: "cateringPackages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  packages?: Array<
    {
      _key: string;
    } & CateringPackage
  >;
};

export type SitePhotos = {
  _id: string;
  _type: "sitePhotos";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  photos?: Array<
    {
      _key: string;
    } & SitePhoto
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tiles?: Array<
    | ({
        _key: string;
      } & GalleryPhotoTile)
    | ({
        _key: string;
      } & GalleryQuoteTile)
  >;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categories?: Array<
    {
      _key: string;
    } & MenuCategory
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | CateringPackage
  | SanityImageAssetReference
  | SitePhoto
  | GalleryQuoteTile
  | GalleryPhotoTile
  | PriceTier
  | Dish
  | MenuCategory
  | CateringPackages
  | SitePhotos
  | SanityImageCrop
  | SanityImageHotspot
  | GalleryPage
  | Menu
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../src/sanity/queries.ts
// Variable: MENU_QUERY
// Query: *[_id == "menu"][0]{    categories[]{      _key,      categoryId,      label,      urdu,      note,      sectionImage{        asset->{          url,          metadata{ lqip, dimensions{ width, height } }        },        hotspot,        crop      },      dishes[]{        _key,        name,        urdu,        desc,        price,        priceTiers[]{ _key, label, price },        spice,        signature,        image{          asset->{            url,            metadata{ lqip, dimensions{ width, height } }          },          hotspot,          crop        },        featured,        featuredOrder      }    }  }
export type MENU_QUERY_RESULT =
  | {
      categories: null;
    }
  | {
      categories: Array<{
        _key: string;
        categoryId: string | null;
        label: string | null;
        urdu: string | null;
        note: string | null;
        sectionImage: {
          asset: {
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        dishes: Array<{
          _key: string;
          name: string | null;
          urdu: string | null;
          desc: string | null;
          price: number | null;
          priceTiers: Array<{
            _key: string;
            label: string | null;
            price: number | null;
          }> | null;
          spice: 0 | 1 | 2 | 3 | null;
          signature: boolean | null;
          image: {
            asset: {
              url: string | null;
              metadata: {
                lqip: string | null;
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
          } | null;
          featured: boolean | null;
          featuredOrder: number | null;
        }> | null;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: SITE_PHOTOS_QUERY
// Query: *[_id == "sitePhotos"][0]{    photos[]{      _key,      key,      caption,      image{        asset->{          url,          metadata{ lqip, dimensions{ width, height } }        },        alt,        hotspot,        crop      }    }  }
export type SITE_PHOTOS_QUERY_RESULT =
  | {
      photos: null;
    }
  | {
      photos: Array<{
        _key: string;
        key:
          | "catering"
          | "food-bbq"
          | "food-karahi"
          | "food-nihari"
          | "food-spread"
          | "founder"
          | "hero-carousel-1"
          | "hero-carousel-2"
          | "hero-carousel-3"
          | "hero-carousel-4"
          | "must-try-4"
          | "occasion-anniversary"
          | "occasion-birthday-party"
          | "occasion-community-mosque"
          | "occasion-corporate-events"
          | "occasion-corporate-lunch"
          | "occasion-daawat"
          | "occasion-dinner-party"
          | "occasion-mehndi"
          | "occasion-walima"
          | "parallax"
          | null;
        caption: string | null;
        image: {
          asset: {
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: CATERING_PACKAGES_QUERY
// Query: *[_id == "cateringPackages"][0]{    packages[]{      _key,      name,      pricePerPerson,      featured,      items    }  }
export type CATERING_PACKAGES_QUERY_RESULT =
  | {
      packages: null;
    }
  | {
      packages: Array<{
        _key: string;
        name: string | null;
        pricePerPerson: number | null;
        featured: boolean | null;
        items: Array<string> | null;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_id == "galleryPage"][0]{    tiles[]{      _key,      _type,      _type == "galleryPhotoTile" => {        role,        image{          asset->{            url,            metadata{ lqip, dimensions{ width, height } }          },          alt,          hotspot,          crop        }      },      _type == "galleryQuoteTile" => {        role,        text      }    }  }
export type GALLERY_QUERY_RESULT =
  | {
      tiles: null;
    }
  | {
      tiles: Array<
        | {
            _key: string;
            _type: "galleryPhotoTile";
            role: "feature" | "normal" | "tall" | "wide" | null;
            image: {
              asset: {
                url: string | null;
                metadata: {
                  lqip: string | null;
                  dimensions: {
                    width: number | null;
                    height: number | null;
                  } | null;
                } | null;
              } | null;
              alt: string | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
          }
        | {
            _key: string;
            _type: "galleryQuoteTile";
            role: "feature" | "normal" | "tall" | "wide" | null;
            text: string | null;
          }
      > | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "menu"][0]{\n    categories[]{\n      _key,\n      categoryId,\n      label,\n      urdu,\n      note,\n      sectionImage{\n        asset->{\n          url,\n          metadata{ lqip, dimensions{ width, height } }\n        },\n        hotspot,\n        crop\n      },\n      dishes[]{\n        _key,\n        name,\n        urdu,\n        desc,\n        price,\n        priceTiers[]{ _key, label, price },\n        spice,\n        signature,\n        image{\n          asset->{\n            url,\n            metadata{ lqip, dimensions{ width, height } }\n          },\n          hotspot,\n          crop\n        },\n        featured,\n        featuredOrder\n      }\n    }\n  }\n': MENU_QUERY_RESULT;
    '\n  *[_id == "sitePhotos"][0]{\n    photos[]{\n      _key,\n      key,\n      caption,\n      image{\n        asset->{\n          url,\n          metadata{ lqip, dimensions{ width, height } }\n        },\n        alt,\n        hotspot,\n        crop\n      }\n    }\n  }\n': SITE_PHOTOS_QUERY_RESULT;
    '\n  *[_id == "cateringPackages"][0]{\n    packages[]{\n      _key,\n      name,\n      pricePerPerson,\n      featured,\n      items\n    }\n  }\n': CATERING_PACKAGES_QUERY_RESULT;
    '\n  *[_id == "galleryPage"][0]{\n    tiles[]{\n      _key,\n      _type,\n      _type == "galleryPhotoTile" => {\n        role,\n        image{\n          asset->{\n            url,\n            metadata{ lqip, dimensions{ width, height } }\n          },\n          alt,\n          hotspot,\n          crop\n        }\n      },\n      _type == "galleryQuoteTile" => {\n        role,\n        text\n      }\n    }\n  }\n': GALLERY_QUERY_RESULT;
  }
}
